name: "Continuous integration"
on:
  push:
  pull_request:

jobs:
  ci:
    name: CI checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        if: ${{ matrix.rust == 'stable' }}
        with:
          toolchain: "1.61.0" # TODO: Pull this from Cargo.toml?
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: ${{ matrix.rust }}
      - run: cargo --version # TODO: Remove
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv,cargo-tarpaulin
      - run: ./scripts/ci/format
      - run: ./scripts/ci/check
      - run: ./scripts/ci/test
      - run: cargo msrv verify
        if: ${{ matrix.rust == 'stable' }}
      - uses: coverallsapp/github-action@v2
        if: ${{ matrix.rust == 'stable' }}
        with:
          file: lcov.info
          format: lcov
