name: "Continuous integration"
on:
  push:
  pull_request:

jobs:
  ci:
    name: CI checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo install just cargo-tarpaulin cargo-msrv
      - run: just format-ci
      - run: just check-ci
      - run: just test-ci
      - run: cargo msrv verify
        if: ${{ matrix.rust == 'stable' }}
      - uses: coverallsapp/github-action@v2
        if: ${{ matrix.rust == 'stable' }}
        with:
          file: lcov.info
          format: lcov
